version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lighthouse
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ../.tmp/postgres:/data/postgres

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
